// 도트 아이콘 — 특성·의뢰·이벤트·보스 능력·버튼 아이콘 (이모지 대신).
// 12×12 문자 격자, 글자 하나가 픽셀 하나('.'은 투명). 4배로 그려 두고 CSS로 24px(2배)·12px(1배)로 줄여 쓴다.
// 주사위 모양 아이콘은 눈 배치로 만든다(dice).

const PAL = {
  k: '#1A1030', w: '#FFFFFF', g: '#FFC83D', G: '#C8860E', r: '#E8435A', R: '#8E2226', o: '#FF8A1A', y: '#FFE27A',
  m: '#3EE6B4', M: '#139B74', b: '#4FB3FF', B: '#2F5FB0', p: '#B98CFF', P: '#5645D0', s: '#C9D3E8', S: '#7A86A8',
  n: '#9A6232', N: '#5A3A1E', c: '#F1DDAE', e: '#6BBE45', E: '#3F7F2A', x: '#8C83BB',
};

const GRIDS = {
  flip: [
    "....kkkk....",
    "..kkmmmmkk..",
    ".kmmkkkkmmk.",
    ".kmk....kmmk",
    "kmk....kmmmk",
    "kmk.....kkk.",
    ".kkk.....kmk",
    "kmmmk....kmk",
    "kmmk....kmk.",
    ".kmmkkkkmmk.",
    "..kkmmmmkk..",
    "....kkkk....",
  ],
  nudge: [
    "...kkkkkk...",
    "..krrrrrrk..",
    ".krrwwwwrrk.",
    "krrwwrrwwrrk",
    "krwwrrrrwwrk",
    "krwrrkkrrwrk",
    "krwrrkkrrwrk",
    "krwwrrrrwwrk",
    "krrwwrrwwrrk",
    ".krrwwwwrrk.",
    "..krrrrrrk..",
    "...kkkkkk...",
  ],
  sheet: [
    "....kkkk....",
    "..kkkggkkk..",
    ".knnkkkknnk.",
    ".knccccccnk.",
    ".knckkkkcnk.",
    ".knccccccnk.",
    ".knckkkkcnk.",
    ".knccccccnk.",
    ".knckkkccnk.",
    ".knccccccnk.",
    ".knnnnnnnnk.",
    "..kkkkkkkk..",
  ],
  scroll: [
    ".kkkkkkkkkk.",
    "kcnccccccnck",
    ".kcccccccck.",
    ".kckkkkkkck.",
    ".kcccccccck.",
    ".kckkkkkcck.",
    ".kcccccccck.",
    ".kckkkkkkck.",
    ".kcccccccck.",
    ".kcccccrrck.",
    "kcnccccrrnck",
    ".kkkkkkkkkk.",
  ],
  sword: [
    ".........kkk",
    "........kwsk",
    ".......kwsk.",
    "......kwsk..",
    ".....kwsk...",
    "..k.kwsk....",
    "..kkwsk.....",
    "...kgk......",
    "..kgkgk.....",
    ".knk.kgk....",
    "knk...k.....",
    "kk..........",
  ],
  swords: [
    "kk........kk",
    "kwk......kwk",
    ".kwk....kwk.",
    "..kwk..kwk..",
    "...kwkkwk...",
    "....kwwk....",
    "....kwwk....",
    "...kgkkgk...",
    "..kgk..kgk..",
    ".knk....knk.",
    "knk......knk",
    "kk........kk",
  ],
  shield: [
    ".kkkkkkkkkk.",
    "kbbbbwwbbbbk",
    "kbbbbwwbbbbk",
    "kbbbbwwbbbbk",
    "kwwwwwwwwwwk",
    "kbbbbwwbbbbk",
    "kBbbbwwbbbBk",
    ".kBbbwwbbBk.",
    ".kBBbwwbBBk.",
    "..kBBwwBBk..",
    "...kBBBBk...",
    "....kkkk....",
  ],
  crown: [
    "............",
    "............",
    "k....kk....k",
    "kk..kggk..kk",
    "kgk.kggk.kgk",
    "kggkggggkggk",
    "kgggggggggGk",
    "kgrggwgggrGk",
    "kggggggggGGk",
    "kGGGGGGGGGGk",
    ".kkkkkkkkkk.",
    "............",
  ],
  belt: [
    "............",
    "............",
    "kkkkkkkkkkkk",
    "kwwwwkkwwwwk",
    "kwwwkrrkwwwk",
    "kkkkkrrkkkkk",
    "....krrk....",
    "...krkkrk...",
    "...krk.krk..",
    "..krk...krk.",
    "..kk.....kk.",
    "............",
  ],
  clover: [
    "..kkk..kkk..",
    ".keeekkeeek.",
    ".keEeeeeEek.",
    "..keeeeeek..",
    ".kkkeeeekkk.",
    "keeeeeeeeeek",
    "keEeeeeeeEek",
    ".keeekkeeek.",
    "..kkk.kkkk..",
    "......knk...",
    ".....knk....",
    ".....kk.....",
  ],
  bolt: [
    "......kkkk..",
    ".....kyyyk..",
    "....kyyyk...",
    "...kyyyk....",
    "..kyyyykkkk.",
    ".kyyyyyyyyk.",
    ".kkkkyyyyk..",
    "....kyyyk...",
    "...kyyyk....",
    "..kyyk......",
    "..kyk.......",
    "..kk........",
  ],
  house: [
    ".....kk.....",
    "....krrk....",
    "...krrrrk...",
    "..krrrrrrk..",
    ".krrrrrrrrk.",
    "kkkkkkkkkkkk",
    ".kcccccccck.",
    ".kcbbcckkck.",
    ".kcbbcknnck.",
    ".kccccknnck.",
    ".kccccknnck.",
    ".kkkkkkkkkk.",
  ],
  boot: [
    "............",
    "..kkkk......",
    "..knnk..kk..",
    "..knnk.kwwk.",
    "..knnkkwwk..",
    "..knnnkwk...",
    "..knnnnk....",
    "..knnnnnkk..",
    "..knnnnnnnk.",
    ".kkkkkkkkkk.",
    "............",
    "............",
  ],
  wolf: [
    "k..........k",
    "kk........kk",
    "ksk......ksk",
    "ksskkkkkkssk",
    "kssssssssssk",
    "ksyksssskysk",
    "kssssssssssk",
    ".kssswwsssk.",
    "..ksskkssk..",
    "...kskksk...",
    "....kkkk....",
    "............",
  ],
  amulet: [
    "....kkkk....",
    "..kkbbbbkk..",
    ".kbbbbbbbbk.",
    ".kbbwwwwbbk.",
    "kbbwwbbwwbbk",
    "kbbwbkkbwbbk",
    "kbbwbkkbwbbk",
    "kbbwwbbwwbbk",
    ".kbbwwwwbbk.",
    ".kbbbbbbbbk.",
    "..kkbbbbkk..",
    "....kkkk....",
  ],
  chain: [
    "............",
    ".kkkk.......",
    "kssssk......",
    "ks..skkkk...",
    "kssssssssk..",
    ".kkkks..sk..",
    "....kssssskk",
    "....kkks..sk",
    "......kssssk",
    ".......kkkk.",
    "............",
    "............",
  ],
  eye: [
    "............",
    "............",
    "...kkkkkk...",
    ".kkwwwwwwkk.",
    "kwwwkbbkwwwk",
    "kwwkbkkbkwwk",
    "kwwkbkkbkwwk",
    "kwwwkbbkwwwk",
    ".kkwwwwwwkk.",
    "...kkkkkk...",
    "............",
    "............",
  ],
  star: [
    ".....kk.....",
    "....kyyk....",
    "....kyyk....",
    "kkkkkyykkkkk",
    "kyyyyyyyyyyk",
    ".kyyywwyyyk.",
    "..kyyyyyyk..",
    "..kyyyyyyk..",
    ".kyyykkyyyk.",
    ".kyyk..kyyk.",
    "kyyk....kyyk",
    "kkk......kkk",
  ],
  boat: [
    ".....k......",
    ".....kk.....",
    ".....kwk....",
    ".....kwwk...",
    ".....kwwwk..",
    ".....kwwwwk.",
    ".....kwwwwwk",
    ".....kkkkkkk",
    "kkkkkkkkkkkk",
    "knnnnnnnnnnk",
    ".knnnnnnnnk.",
    "..kkkkkkkk..",
  ],
  toolbox: [
    "............",
    "....kkkk....",
    "...kk..kk...",
    "kkkkkkkkkkkk",
    "krrrrrrrrrrk",
    "krrrrrrrrrrk",
    "kkkkkggkkkkk",
    "kRRRRggRRRRk",
    "kRRRRRRRRRRk",
    "kRRRRRRRRRRk",
    "kkkkkkkkkkkk",
    "............",
  ],
  bag: [
    "....kkkk....",
    "...kk..kk...",
    ".kkkkkkkkkk.",
    "knnnnnnnnnnk",
    "knnnnnnnnnnk",
    "kkkkkkkkkkkk",
    "knnnkggknnnk",
    "knnnkkkknnnk",
    "knnnnnnnnnnk",
    "kNnnnnnnnnNk",
    ".kkkkkkkkkk.",
    "............",
  ],
  medal: [
    "..kkk..kkk..",
    "..krk..kbk..",
    "...krkkbk...",
    "....krbk....",
    "....kkkk....",
    "...kggggk...",
    "..kggyyggk..",
    "..kgyggygk..",
    "..kggyyggk..",
    "..kGggggGk..",
    "...kGGGGk...",
    "....kkkk....",
  ],
  mountain: [
    "............",
    ".....kk.....",
    "....kwwk....",
    "...kwwwwk...",
    "...ksssssk..",
    "..kssssssk..",
    "..ksSssSssk.",
    ".kssSSssSssk",
    ".ksSSSSSSSsk",
    "kSSSSSSSSSSk",
    "kkkkkkkkkkkk",
    "............",
  ],
  snake: [
    "............",
    "......kkkk..",
    ".....keeeek.",
    ".....kekeek.",
    "......keeek.",
    "..kkkk.keek.",
    ".keeeekeek..",
    "keekkeeek...",
    "kek..kkk....",
    "keek........",
    ".keeeek.....",
    "..kkkk......",
  ],
  hole: [
    "............",
    "............",
    "............",
    "..kkkkkkkk..",
    ".kNNNNNNNNk.",
    "kNkkkkkkkkNk",
    "kNkkkkkkkkNk",
    ".kNNkkkkNNk.",
    "..kkNNNNkk..",
    "....kkkk....",
    "............",
    "............",
  ],
  rainbow: [
    "............",
    "...kkkkkk...",
    ".kkrrrrrrkk.",
    "krrggggggrrk",
    "krggmmmmggrk",
    "krgmkkkkmgrk",
    "krgmk..kmgrk",
    "krgmk..kmgrk",
    "kkkkk..kkkkk",
    "............",
    "............",
    "............",
  ],
  horn: [
    "............",
    ".........kk.",
    "........kggk",
    "kk.....kgggk",
    "kgkkkkkggggk",
    "kgggggggggGk",
    "kgkkkkkggggk",
    "kk..k..kgggk",
    "...kgk..kggk",
    "...kkk...kk.",
    "............",
    "............",
  ],
  castle: [
    "k.k.k..k.k.k",
    "kkkkk..kkkkk",
    "ksssk..ksssk",
    "kssskkkksssk",
    "kssssssssssk",
    "kskssssssksk",
    "kssssssssssk",
    "ksssskkssssk",
    "ksssknnksssk",
    "ksssknnksssk",
    "kkkkkkkkkkkk",
    "............",
  ],
  skull: [
    "..kkkkkkkk..",
    ".kwwwwwwwwk.",
    "kwwwwwwwwwwk",
    "kwkkwwwwkkwk",
    "kwkkwwwwkkwk",
    "kwwwwkkwwwwk",
    ".kwwwkkwwwk.",
    "..kwwwwwwk..",
    "..kwkwwkwk..",
    "..kkkkkkkk..",
    "............",
    "............",
  ],
  lock: [
    "....kkkk....",
    "...kssssk...",
    "..ks.kk.sk..",
    "..ks.kk.sk..",
    "..ks....sk..",
    ".kkkkkkkkkk.",
    ".kggggggggk.",
    ".kggGkkGggk.",
    ".kgggkkgggk.",
    ".kgggkkgggk.",
    ".kGGGGGGGGk.",
    ".kkkkkkkkkk.",
  ],
  fist: [
    "...kkkkkk...",
    "..kccckccck.",
    ".kcckcckcck.",
    ".kcckcckcckk",
    "kkcckcckccck",
    "kcckkkkkkcck",
    "kccccccccck.",
    "kccccccccck.",
    ".kcccccccck.",
    "..kccccccck.",
    "...kkkkkkk..",
    "............",
  ],
  hourglass: [
    ".kkkkkkkkkk.",
    ".knnnnnnnnk.",
    "..kyyyyyyk..",
    "..kyyyyyyk..",
    "...kyyyyk...",
    "....kyyk....",
    "....kwwk....",
    "...kwwywk...",
    "..kwwyyywk..",
    "..kyyyyyyk..",
    ".knnnnnnnnk.",
    ".kkkkkkkkkk.",
  ],
  axe: [
    "..kkkk......",
    ".ksssskk....",
    "ksssssknk...",
    "ksssssknk...",
    ".ksssskkk...",
    "..kkkk.knk..",
    ".......knk..",
    "........knk.",
    "........knk.",
    ".........knk",
    ".........kkk",
    "............",
  ],
  yinyang: [
    "....kkkk....",
    "..kkwwwwkk..",
    ".kwwwwwwPPk.",
    ".kwwwPwPPPk.",
    "kwwwwwwPPPPk",
    "kwwwwwPPPPPk",
    "kwwwwPPPPPPk",
    "kwwwPPPwPPPk",
    ".kwwPPPPPPk.",
    ".kwPPPPPPPk.",
    "..kkPPPPkk..",
    "....kkkk....",
  ],
  scale: [
    ".....kk.....",
    "kkkkkggkkkkk",
    ".k...gg...k.",
    "k.k..gg..k.k",
    "k..k.gg.k..k",
    "kgggkggkgggk",
    ".kkk.gg.kkk.",
    ".....gg.....",
    ".....gg.....",
    "...kkggkk...",
    "..kggggggk..",
    "..kkkkkkkk..",
  ],
  heart: [
    ".kkk....kkk.",
    "krrrk..krrrk",
    "krwrrkkrrrrk",
    "krrrrrrrrrrk",
    "krrrrrrrrrrk",
    ".krrrrrrrrk.",
    "..krrrrrrk..",
    "...krrrrk...",
    "....krrk....",
    ".....kk.....",
    "............",
    "............",
  ],
  sun: [
    "..k..k......",
    "...kyyk.k...",
    ".kyyyyyk....",
    "kyyyyyyyk...",
    ".kyyykkkkk..",
    "kyyykwwwwwk.",
    ".kykwwwwwwwk",
    "..kwwwwwwwwk",
    "...kkkkkkkk.",
    "............",
    "............",
    "............",
  ],
  party: [
    "........r..g",
    "..m...b.....",
    ".......g..r.",
    "....r.......",
    "...kk..m..b.",
    "..kgk.......",
    "..kggk..r...",
    ".kgggk......",
    ".kggGGk.....",
    "kgggGGk.....",
    "kGGGGGGk....",
    "kkkkkkkk....",
  ],
  fog: [
    "............",
    "..xxxxxx....",
    "............",
    "xxxxxxxxxx..",
    "............",
    "...xxxxxxxxx",
    "............",
    "xxxxxxxx....",
    "............",
    "..xxxxxxxxx.",
    "............",
    "............",
  ],
  leaf: [
    "..........kk",
    ".......kkkek",
    ".....kkeeeek",
    "....keeeeek.",
    "...keeEeeek.",
    "..keeEeeek..",
    "..keEeeek...",
    ".keEeekk....",
    ".kEekk......",
    "kEk.........",
    "kk..........",
    "............",
  ],
  money: [
    "....kkkk....",
    ".....kk.....",
    "....kGGk....",
    "...kggggk...",
    "..kgggkggk..",
    ".kggkkkkggk.",
    ".kgggkggggk.",
    ".kggggkkggk.",
    ".kggkkkkggk.",
    ".kGgggkgggk.",
    "..kGGGGGGk..",
    "...kkkkkk...",
  ],
  lotus: [
    "............",
    ".....kk.....",
    "....kppk....",
    "....kppk....",
    ".kk.kppk.kk.",
    "kppkkppkkppk",
    ".kppkppkppk.",
    "..kppppppk..",
    "kkkkkkkkkkkk",
    ".kmmmmmmmmk.",
    "..kkkkkkkk..",
    "............",
  ],
  coins: [
    "....kkkk....",
    "...kggggk...",
    "...kGGGGk...",
    "...kggggk...",
    "..kkGGGGkk..",
    ".kgggkkgggk.",
    ".kGGGGGGGGk.",
    ".kggggggggk.",
    ".kGGGGGGGGk.",
    "kkkkkkkkkkkk",
    "kgggggggggGk",
    "kkkkkkkkkkkk",
  ],
  wheat: [
    ".kk..kk..kk.",
    "kgk.kggk.kgk",
    "kgk.kggk.kgk",
    ".kgkkggkkgk.",
    ".kgkkggkkgk.",
    "..kGkGGkGk..",
    "...kGGGGk...",
    "....kGGk....",
    "....kGGk....",
    "....kGGk....",
    "....kGGk....",
    "....kkkk....",
  ],
  trophy: [
    ".kkkkkkkkkk.",
    "kkggggggggkk",
    "kgkggggggkgk",
    "kgkgggyggkgk",
    ".kkggggggkk.",
    "...kggggk...",
    "....kggk....",
    ".....kk.....",
    "....kGGk....",
    "...kggggk...",
    "..kGGGGGGk..",
    "..kkkkkkkk..",
  ],
  sparkle: [
    ".....kk.....",
    ".....yy.....",
    "....kyyk....",
    "kkyyywwyyykk",
    "....kyyk....",
    ".....yy.....",
    ".....kk..k..",
    "........kyk.",
    ".k.....kywyk",
    "kyk.....kyk.",
    ".k.......k..",
    "............",
  ],
  fire: [
    ".....k......",
    "....kok.....",
    "...kook..k..",
    "...koook.kk.",
    "..kooyookok.",
    ".kooyyyoook.",
    ".koyyyyyook.",
    "kooyywyyyook",
    "kooyywwyyook",
    ".kooyyyyook.",
    "..kooooook..",
    "...kkkkkk...",
  ],
  anger: [
    "..kk....kk..",
    "..krk..krk..",
    "kkkrk..krkkk",
    "krrrk..krrrk",
    "kkkk....kkkk",
    "............",
    "............",
    "kkkk....kkkk",
    "krrrk..krrrk",
    "kkkrk..krkkk",
    "..krk..krk..",
    "..kk....kk..",
  ],
  drum: [
    "k..........k",
    ".k........k.",
    "..k......k..",
    ".kkkkkkkkkk.",
    "kwwwwwwwwwwk",
    "kkwwwwwwwwkk",
    "krkkkkkkkkrk",
    "krrkrrrkrrrk",
    "krkrrrkrrrrk",
    "krrrrrrrrrrk",
    ".kkkkkkkkkk.",
    "............",
  ],
  vortex: [
    "..kkkkkkk...",
    ".kpppppppk..",
    "kpkkkkkkkpk.",
    "kpk.kkkk.kpk",
    "kpk.kppk.kpk",
    "kpk..kpk.kpk",
    "kpkkkkpk.kpk",
    ".kppppk..kpk",
    "..kkkk..kpk.",
    "........kpk.",
    "...kkkkkpk..",
    "..kpppppk...",
  ],
  warn: [
    ".....kk.....",
    "....kyyk....",
    "....kyyk....",
    "...kyyyyk...",
    "...kykkyk...",
    "..kyykkyyk..",
    "..kyykkyyk..",
    ".kyyyyyyyyk.",
    ".kyyykkyyyk.",
    "kyyyykkyyyyk",
    "kkkkkkkkkkkk",
    "............",
  ],
  up: [
    ".....kk.....",
    "....kmmk....",
    "...kmmmmk...",
    "..kmmmmmmk..",
    ".kmmmmmmmmk.",
    "kkkkmmmmkkkk",
    "...kmmmmk...",
    "...kmmmmk...",
    "...kmmmmk...",
    "...kmmmmk...",
    "...kkkkkk...",
    "............",
  ],
  cap: [
    "............",
    ".....kk.....",
    "...kkPPkk...",
    ".kkPPPPPPkk.",
    "kPPPPPPPPPPk",
    ".kkPPPPPPkkg",
    "..kkkkkkkk.g",
    "..kPPPPPPk.g",
    "..kPPPPPPk.k",
    "...kkkkkk...",
    "............",
    "............",
  ],
  door: [
    "..kkkkkkkk..",
    "..knnnnnnk..",
    "..knNnnNnk..",
    "..knNnnNnk..",
    "..knnnnnnk..",
    "..knnnnngk..",
    "..knNnnNnk..",
    "..knNnnNnk..",
    "..knnnnnnk..",
    "..knnnnnnk..",
    "kkkkkkkkkkkk",
    "............",
  ],
  beads: [
    "....kkkk....",
    "..kkrkkrkk..",
    ".krk....krk.",
    ".kk......kk.",
    "krk......krk",
    "kk........kk",
    "krk......krk",
    ".kk......kk.",
    ".krk....krk.",
    "..kkrkkrkk..",
    "....kggk....",
    "....kkkk....",
  ],
  mouse: [
    "............",
    ".kk....kk...",
    "kssk..kssk..",
    "ksskkkkssk..",
    ".kssssssk...",
    ".kskssksk...",
    "kssssssssk..",
    "kssssrssskk.",
    ".kssssssk..k",
    "..kkkkkk..k.",
    "..........k.",
    "............",
  ]
};

// 같은 그림에 색만 바꾼 것
const ALIAS = {
  recycle: ['flip', { m: '#6BBE45' }],
  dscale: ['shield', { b: '#E8435A', B: '#8E2226', w: '#FFC83D' }],
  bone: ['shield', { b: '#F2EEDD', B: '#B8AE92', w: '#9486FF' }],
  volcano: ['mountain', { s: '#E8435A', S: '#8E2226', w: '#FFB02E' }],
  dagger: ['sword', { s: '#B98CFF' }],
  link: ['chain', {}],
};

// 주사위: 눈 v, 몸통 색 face. 12×12
const PIP = { 1: [[5, 5]], 2: [[2, 2], [8, 8]], 3: [[2, 2], [5, 5], [8, 8]], 4: [[2, 2], [8, 2], [2, 8], [8, 8]],
  5: [[2, 2], [8, 2], [5, 5], [2, 8], [8, 8]], 6: [[2, 2], [8, 2], [2, 5], [8, 5], [2, 8], [8, 8]] };
function dieGrid(v) {
  const g = [...Array(12)].map((_, y) => [...Array(12)].map((_, x) => {
    const edge = x === 0 || y === 0 || x === 11 || y === 11;
    const corner = (x === 0 || x === 11) && (y === 0 || y === 11);
    return corner ? '.' : edge ? 'k' : 'w';
  }));
  for (const [x, y] of PIP[v]) for (const [dx, dy] of [[0, 0], [1, 0], [0, 1], [1, 1]]) g[y + dy][x + dx] = v === 1 ? 'r' : 'k';
  return g.map(r => r.join(''));
}
// 작은 주사위 두 개 (쌍)
function pairGrid(v) {
  const g = [...Array(12)].map(() => [...Array(12)].fill('.'));
  const small = (ox, oy) => {
    for (let y = 0; y < 7; y++) for (let x = 0; x < 7; x++) {
      const corner = (x === 0 || x === 6) && (y === 0 || y === 6);
      if (corner) continue;
      g[oy + y][ox + x] = x === 0 || y === 0 || x === 6 || y === 6 ? 'k' : 'w';
    }
    const pts = v === 6 ? [[2, 2], [4, 2], [2, 3], [4, 3], [2, 4], [4, 4]] : [[2, 2], [4, 4]];
    for (const [x, y] of pts) g[oy + y][ox + x] = 'k';
  };
  small(0, 0); small(5, 5);
  return g.map(r => r.join(''));
}

const cache = new Map();
function grid(name) {
  if (GRIDS[name]) return { rows: GRIDS[name], pal: PAL };
  if (ALIAS[name]) { const [base, over] = ALIAS[name]; return { rows: GRIDS[base], pal: { ...PAL, ...over } }; }
  let m = /^die(\d)(\w*)$/.exec(name);
  if (m) return { rows: dieGrid(Number(m[1])), pal: m[2] ? { ...PAL, w: PAL[m[2]] || PAL.w } : PAL };
  m = /^pair(\d)$/.exec(name);
  if (m) return { rows: pairGrid(Number(m[1])), pal: PAL };
  return { rows: GRIDS.sparkle, pal: PAL };
}

export function iconURL(name) {
  if (cache.has(name)) return cache.get(name);
  const { rows, pal } = grid(name);
  const S = 4;
  const c = document.createElement('canvas');
  c.width = c.height = 12 * S;
  const g = c.getContext('2d');
  rows.forEach((row, y) => [...row].forEach((ch, x) => {
    if (ch === '.') return;
    g.fillStyle = pal[ch];
    g.fillRect(x * S, y * S, S, S);
  }));
  const url = c.toDataURL();
  cache.set(name, url);
  return url;
}

// <img> 태그. cls: '' 24px · 'xs' 12px · 'lg' 48px
export const ico = (name, cls = '') => `<img class="ico${cls ? ' ' + cls : ''}" src="${iconURL(name)}" alt="">`;

export const PERK_ICON = {
  flip: 'flip', nudge: 'nudge', basic: 'belt', choice: 'clover', fame: 'scroll', fast: 'bolt', insure: 'shield',
  full: 'house', straight: 'boot', fourk: 'wolf', reroll: 'recycle', lucky: 'amulet', chain: 'chain', scholar: 'eye',
  sixth: 'star', midas: 'crown', yacht: 'boat', toolkit: 'toolbox', nudgeBag: 'bag', bigKit: 'medal',
};
export const QUEST_ICON = {
  pairs: 'pair2', triple: 'swords', high: 'mountain', high2: 'volcano', low: 'snake', low2: 'hole', even: 'shield',
  odd: 'dagger', rainbow: 'rainbow', house: 'house', sstr: 'boot', lstr: 'horn', quad: 'castle', six3: 'die6g',
  one3: 'skull', ends: 'axe', middle: 'yinyang', sum20: 'scale', sum17: 'clover', noSix: 'heart', twoSix: 'pair6',
  big3: 'die5', small4: 'mouse', yacht: 'boat',
  oneShot: 'bolt', bare: 'fist', last: 'hourglass', twin: 'star', sum15: 'medal',
};
export const EVENT_ICON = {
  calm: 'sun', festival: 'party', fog: 'fog', wind: 'leaf', bounty: 'money', zen: 'lotus', jackpot: 'coins',
  harvest: 'wheat', duel: 'trophy', refresh: 'sheet', blessing: 'sparkle',
};
export const SKILL_ICON = {
  breath: 'fire', scale: 'dscale', rage: 'anger', drums: 'drum', plunder: 'money', twist: 'vortex', bone: 'bone',
};
